name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild native directories
        run: npx expo prebuild --platform android --clean --no-install

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RaidSiren-APK
          path: android/app/build/outputs/apk/release/app-release.apk
